In [1]:
import numpy
import pandas

In [2]:
# Series对象
s=pandas.Series([1,2,5,numpy.nan,6,8])
s

0    1.0
1    2.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [3]:
# DataFrame对象
dates=pandas.date_range("20130101",periods=6) # 生成时间戳索引对象
# 以时间戳为指定的索引项，构造DataFrame，列名分别为ABCD，数据由numpy随机生成
df=pandas.DataFrame(numpy.random.randn(6,4),index=dates,columns=['A','B','C','D'])
df

                   A         B         C         D
2013-01-01 -0.165288 -0.504111  1.295944  1.217030
2013-01-02  0.141751  0.682408 -1.155090  1.151839
2013-01-03 -2.564487  0.412872  0.226316 -1.032376
2013-01-04 -3.398212 -0.719237  0.895835 -0.128436
2013-01-05 -0.401212  0.511683 -1.426319 -0.572777
2013-01-06 -0.076830  0.326643 -1.209414 -0.520118

In [4]:
# 另一种构造DataFrame的方式
df2 = pandas.DataFrame({
    'A':1.0,
    'B':pandas.Timestamp("20130102"),
    'C':pandas.Series(1,index=list(range(4)),dtype="float32"),
    'D':numpy.array([3,3,3,3],dtype="int32"),
    'E':pandas.Categorical(["test","train","test","train"]),
    'F':"FOO"
})
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  FOO
1  1.0 2013-01-02  1.0  3  train  FOO
2  1.0 2013-01-02  1.0  3   test  FOO
3  1.0 2013-01-02  1.0  3  train  FOO

In [5]:
df2.dtypes # 各字段的类型

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [6]:
df2.A # 查看某列数据

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64

In [7]:
# 查看头部数据，默认为前5条
df.head()

                   A         B         C         D
2013-01-01 -0.165288 -0.504111  1.295944  1.217030
2013-01-02  0.141751  0.682408 -1.155090  1.151839
2013-01-03 -2.564487  0.412872  0.226316 -1.032376
2013-01-04 -3.398212 -0.719237  0.895835 -0.128436
2013-01-05 -0.401212  0.511683 -1.426319 -0.572777

In [8]:
# 查看尾部数据，默认为后5条
df.tail()

                   A         B         C         D
2013-01-02  0.141751  0.682408 -1.155090  1.151839
2013-01-03 -2.564487  0.412872  0.226316 -1.032376
2013-01-04 -3.398212 -0.719237  0.895835 -0.128436
2013-01-05 -0.401212  0.511683 -1.426319 -0.572777
2013-01-06 -0.076830  0.326643 -1.209414 -0.520118

In [9]:
# 转换为numpy数组
df.to_numpy()

array([[-0.16528849, -0.50411082,  1.29594401,  1.21702982],
       [ 0.14175122,  0.6824081 , -1.15508967,  1.15183885],
       [-2.5644869 ,  0.41287184,  0.2263161 , -1.03237649],
       [-3.39821221, -0.71923723,  0.89583494, -0.12843603],
       [-0.40121224,  0.51168306, -1.42631922, -0.57277721],
       [-0.07682974,  0.32664257, -1.20941353, -0.52011767]])

In [10]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'FOO'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'FOO'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'FOO'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'FOO']],
      dtype=object)

In [11]:
# 描述性统计信息
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -1.077380  0.118376 -0.228788  0.019194
std    1.508260  0.581724  1.187472  0.947267
min   -3.398212 -0.719237 -1.426319 -1.032376
25%   -2.023668 -0.296422 -1.195833 -0.559612
50%   -0.283250  0.369757 -0.464387 -0.324277
75%   -0.098944  0.486980  0.728455  0.831770
max    0.141751  0.682408  1.295944  1.217030

In [12]:
# 转置
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.165288    0.141751   -2.564487   -3.398212   -0.401212   -0.076830
B   -0.504111    0.682408    0.412872   -0.719237    0.511683    0.326643
C    1.295944   -1.155090    0.226316    0.895835   -1.426319   -1.209414
D    1.217030    1.151839   -1.032376   -0.128436   -0.572777   -0.520118

In [13]:
# 按字段排序，axis表示轴，1是按列排序，0是按索引排序
df.sort_index(axis=0,ascending=False)

                   A         B         C         D
2013-01-06 -0.076830  0.326643 -1.209414 -0.520118
2013-01-05 -0.401212  0.511683 -1.426319 -0.572777
2013-01-04 -3.398212 -0.719237  0.895835 -0.128436
2013-01-03 -2.564487  0.412872  0.226316 -1.032376
2013-01-02  0.141751  0.682408 -1.155090  1.151839
2013-01-01 -0.165288 -0.504111  1.295944  1.217030

In [14]:
# 按指定字段排序
df.sort_values(by="B")

                   A         B         C         D
2013-01-04 -3.398212 -0.719237  0.895835 -0.128436
2013-01-01 -0.165288 -0.504111  1.295944  1.217030
2013-01-06 -0.076830  0.326643 -1.209414 -0.520118
2013-01-03 -2.564487  0.412872  0.226316 -1.032376
2013-01-05 -0.401212  0.511683 -1.426319 -0.572777
2013-01-02  0.141751  0.682408 -1.155090  1.151839

## Selection

In [15]:
# 按字段选取
df["A"]

2013-01-01   -0.165288
2013-01-02    0.141751
2013-01-03   -2.564487
2013-01-04   -3.398212
2013-01-05   -0.401212
2013-01-06   -0.076830
Freq: D, Name: A, dtype: float64

In [16]:
# 按索引号选取
df[0:3]

                   A         B         C         D
2013-01-01 -0.165288 -0.504111  1.295944  1.217030
2013-01-02  0.141751  0.682408 -1.155090  1.151839
2013-01-03 -2.564487  0.412872  0.226316 -1.032376

In [17]:
# 按索引值选取
df["20130102":"20130104"]

                   A         B         C         D
2013-01-02  0.141751  0.682408 -1.155090  1.151839
2013-01-03 -2.564487  0.412872  0.226316 -1.032376
2013-01-04 -3.398212 -0.719237  0.895835 -0.128436

In [18]:
# 使用loc方法选取指定索引值对应的一行
df.loc["20130101"]

A   -0.165288
B   -0.504111
C    1.295944
D    1.217030
Name: 2013-01-01 00:00:00, dtype: float64

In [19]:
# 获取指定行列对应的区域，先行后列
df.loc[:,["A","B"]]

                   A         B
2013-01-01 -0.165288 -0.504111
2013-01-02  0.141751  0.682408
2013-01-03 -2.564487  0.412872
2013-01-04 -3.398212 -0.719237
2013-01-05 -0.401212  0.511683
2013-01-06 -0.076830  0.326643

In [20]:
df.loc["20130101","A"]

-0.16528849181747268

In [21]:
# 等价于
df.at["20130101","A"]

-0.16528849181747268

In [22]:
# 使用iloc方法，通过行列索引值，也是先行后列
df.iloc[3]

A   -3.398212
B   -0.719237
C    0.895835
D   -0.128436
Name: 2013-01-04 00:00:00, dtype: float64

In [23]:
df.iloc[1:3,2:4]

                   C         D
2013-01-02 -1.155090  1.151839
2013-01-03  0.226316 -1.032376

In [24]:
df.iloc[[1,2,4],[0,2]]

                   A         C
2013-01-02  0.141751 -1.155090
2013-01-03 -2.564487  0.226316
2013-01-05 -0.401212 -1.426319

In [25]:
df.iloc[2,3]

-1.03237648959125

In [26]:
# 等价于
df.iat[2,3]

-1.03237648959125

In [27]:
# 按条件选择
df[df['A']>0]

                   A         B        C         D
2013-01-02  0.141751  0.682408 -1.15509  1.151839

In [28]:
df2=df.copy()
df2["E"]=[2,3,4,3,2,5]
df2[df2["E"].isin([2,3])]

                   A         B         C         D  E
2013-01-01 -0.165288 -0.504111  1.295944  1.217030  2
2013-01-02  0.141751  0.682408 -1.155090  1.151839  3
2013-01-04 -3.398212 -0.719237  0.895835 -0.128436  3
2013-01-05 -0.401212  0.511683 -1.426319 -0.572777  2

In [29]:
# 赋值
df.at[dates[0],'A']=0
df.iat[0,1]=0.2
df.loc[:,'D']=[5]*len(df)
df

                   A         B         C  D
2013-01-01  0.000000  0.200000  1.295944  5
2013-01-02  0.141751  0.682408 -1.155090  5
2013-01-03 -2.564487  0.412872  0.226316  5
2013-01-04 -3.398212 -0.719237  0.895835  5
2013-01-05 -0.401212  0.511683 -1.426319  5
2013-01-06 -0.076830  0.326643 -1.209414  5

In [30]:
df2=df.copy()
# 对大于0的单元格取负值
df2[df2>0]=-df2
df2

                   A         B         C  D
2013-01-01  0.000000 -0.200000 -1.295944 -5
2013-01-02 -0.141751 -0.682408 -1.155090 -5
2013-01-03 -2.564487 -0.412872 -0.226316 -5
2013-01-04 -3.398212 -0.719237 -0.895835 -5
2013-01-05 -0.401212 -0.511683 -1.426319 -5
2013-01-06 -0.076830 -0.326643 -1.209414 -5

### 缺省值

In [31]:
dd=df.any(axis=1)
dd

2013-01-01    True
2013-01-02    True
2013-01-03    True
2013-01-04    True
2013-01-05    True
2013-01-06    True
Freq: D, dtype: bool

In [32]:
df[dd]

                   A         B         C  D
2013-01-01  0.000000  0.200000  1.295944  5
2013-01-02  0.141751  0.682408 -1.155090  5
2013-01-03 -2.564487  0.412872  0.226316  5
2013-01-04 -3.398212 -0.719237  0.895835  5
2013-01-05 -0.401212  0.511683 -1.426319  5
2013-01-06 -0.076830  0.326643 -1.209414  5

In [34]:
dd.iloc[2]=False
dd

2013-01-01     True
2013-01-02     True
2013-01-03    False
2013-01-04     True
2013-01-05     True
2013-01-06     True
Freq: D, dtype: bool

In [35]:
df[dd]

                   A         B         C  D
2013-01-01  0.000000  0.200000  1.295944  5
2013-01-02  0.141751  0.682408 -1.155090  5
2013-01-04 -3.398212 -0.719237  0.895835  5
2013-01-05 -0.401212  0.511683 -1.426319  5
2013-01-06 -0.076830  0.326643 -1.209414  5