In [1]:
import numpy
import pandas

In [2]:
# Series对象
s=pandas.Series([1,2,5,numpy.nan,6,8])
s

0    1.0
1    2.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [6]:
# DataFrame对象
dates=pandas.date_range("20130101",periods=6) # 生成时间戳索引对象
# 以时间戳为指定的索引项，构造DataFrame，列名分别为ABCD，数据由numpy随机生成
df=pandas.DataFrame(numpy.random.randn(6,4),index=dates,columns=['A','B','C','D'])
df

                   A         B         C         D
2013-01-01  0.669801  1.048827 -1.585766 -0.749194
2013-01-02  0.757677  0.262206  1.266002  1.030052
2013-01-03  1.976971  0.787396  0.455361  0.498305
2013-01-04  1.021397  0.172707 -0.580595  0.729541
2013-01-05 -0.922721  0.722249  1.438161 -0.833204
2013-01-06 -0.200188  1.524352  0.238962  2.860210

In [8]:
# 另一种构造DataFrame的方式
df2 = pandas.DataFrame({
    'A':1.0,
    'B':pandas.Timestamp("20130102"),
    'C':pandas.Series(1,index=list(range(4)),dtype="float32"),
    'D':numpy.array([3,3,3,3],dtype="int32"),
    'E':pandas.Categorical(["test","train","test","train"]),
    'F':"FOO"
})
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  FOO
1  1.0 2013-01-02  1.0  3  train  FOO
2  1.0 2013-01-02  1.0  3   test  FOO
3  1.0 2013-01-02  1.0  3  train  FOO

In [9]:
df2.dtypes # 各字段的类型

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [10]:
df2.A # 查看某列数据

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64

In [11]:
# 查看头部数据，默认为前5条
df.head()

                   A         B         C         D
2013-01-01  0.669801  1.048827 -1.585766 -0.749194
2013-01-02  0.757677  0.262206  1.266002  1.030052
2013-01-03  1.976971  0.787396  0.455361  0.498305
2013-01-04  1.021397  0.172707 -0.580595  0.729541
2013-01-05 -0.922721  0.722249  1.438161 -0.833204

In [12]:
# 查看尾部数据，默认为后5条
df.tail()

                   A         B         C         D
2013-01-02  0.757677  0.262206  1.266002  1.030052
2013-01-03  1.976971  0.787396  0.455361  0.498305
2013-01-04  1.021397  0.172707 -0.580595  0.729541
2013-01-05 -0.922721  0.722249  1.438161 -0.833204
2013-01-06 -0.200188  1.524352  0.238962  2.860210

In [13]:
# 转换为numpy数组
df.to_numpy()

array([[ 0.6698008 ,  1.04882744, -1.58576642, -0.74919363],
       [ 0.757677  ,  0.26220625,  1.26600168,  1.03005232],
       [ 1.97697076,  0.78739646,  0.45536146,  0.49830542],
       [ 1.02139699,  0.17270737, -0.58059506,  0.7295411 ],
       [-0.92272068,  0.72224851,  1.43816061, -0.83320415],
       [-0.20018807,  1.52435189,  0.23896159,  2.86021021]])

In [15]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'FOO'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'FOO'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'FOO'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'FOO']],
      dtype=object)

In [20]:
# 描述性统计信息
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.550489  0.752956  0.205354  0.589285
std    1.004752  0.502443  1.143175  1.356048
min   -0.922721  0.172707 -1.585766 -0.833204
25%    0.017309  0.377217 -0.375706 -0.437319
50%    0.713739  0.754822  0.347162  0.613923
75%    0.955467  0.983470  1.063342  0.954925
max    1.976971  1.524352  1.438161  2.860210

In [21]:
# 转置
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.669801    0.757677    1.976971    1.021397   -0.922721   -0.200188
B    1.048827    0.262206    0.787396    0.172707    0.722249    1.524352
C   -1.585766    1.266002    0.455361   -0.580595    1.438161    0.238962
D   -0.749194    1.030052    0.498305    0.729541   -0.833204    2.860210

In [24]:
# 按字段排序，axis表示轴，1是按列排序，0是按索引排序
df.sort_index(axis=0,ascending=False)

                   A         B         C         D
2013-01-06 -0.200188  1.524352  0.238962  2.860210
2013-01-05 -0.922721  0.722249  1.438161 -0.833204
2013-01-04  1.021397  0.172707 -0.580595  0.729541
2013-01-03  1.976971  0.787396  0.455361  0.498305
2013-01-02  0.757677  0.262206  1.266002  1.030052
2013-01-01  0.669801  1.048827 -1.585766 -0.749194

In [25]:
# 按指定字段排序
df.sort_values(by="B")

                   A         B         C         D
2013-01-04  1.021397  0.172707 -0.580595  0.729541
2013-01-02  0.757677  0.262206  1.266002  1.030052
2013-01-05 -0.922721  0.722249  1.438161 -0.833204
2013-01-03  1.976971  0.787396  0.455361  0.498305
2013-01-01  0.669801  1.048827 -1.585766 -0.749194
2013-01-06 -0.200188  1.524352  0.238962  2.860210

## Selection

In [27]:
# 按字段选取
df["A"]

2013-01-01    0.669801
2013-01-02    0.757677
2013-01-03    1.976971
2013-01-04    1.021397
2013-01-05   -0.922721
2013-01-06   -0.200188
Freq: D, Name: A, dtype: float64

In [28]:
# 按索引号选取
df[0:3]

                   A         B         C         D
2013-01-01  0.669801  1.048827 -1.585766 -0.749194
2013-01-02  0.757677  0.262206  1.266002  1.030052
2013-01-03  1.976971  0.787396  0.455361  0.498305

In [29]:
# 按索引值选取
df["20130102":"20130104"]

                   A         B         C         D
2013-01-02  0.757677  0.262206  1.266002  1.030052
2013-01-03  1.976971  0.787396  0.455361  0.498305
2013-01-04  1.021397  0.172707 -0.580595  0.729541

In [30]:
# 使用loc方法选取指定索引值对应的一行
df.loc["20130101"]

A    0.669801
B    1.048827
C   -1.585766
D   -0.749194
Name: 2013-01-01 00:00:00, dtype: float64

In [31]:
# 获取指定行列对应的区域，先行后列
df.loc[:,["A","B"]]

                   A         B
2013-01-01  0.669801  1.048827
2013-01-02  0.757677  0.262206
2013-01-03  1.976971  0.787396
2013-01-04  1.021397  0.172707
2013-01-05 -0.922721  0.722249
2013-01-06 -0.200188  1.524352

In [33]:
df.loc["20130101","A"]

0.6698008022561356

In [36]:
# 等价于
df.at["20130101","A"]

0.6698008022561356

In [37]:
# 使用iloc方法，通过行列索引值，也是先行后列
df.iloc[3]

A    1.021397
B    0.172707
C   -0.580595
D    0.729541
Name: 2013-01-04 00:00:00, dtype: float64

In [39]:
df.iloc[1:3,2:4]

                   C         D
2013-01-02  1.266002  1.030052
2013-01-03  0.455361  0.498305

In [40]:
df.iloc[[1,2,4],[0,2]]

                   A         C
2013-01-02  0.757677  1.266002
2013-01-03  1.976971  0.455361
2013-01-05 -0.922721  1.438161

In [41]:
df.iloc[2,3]

0.49830542128092237

In [42]:
# 等价于
df.iat[2,3]

0.49830542128092237

In [43]:
# 按条件选择
df[df['A']>0]

                   A         B         C         D
2013-01-01  0.669801  1.048827 -1.585766 -0.749194
2013-01-02  0.757677  0.262206  1.266002  1.030052
2013-01-03  1.976971  0.787396  0.455361  0.498305
2013-01-04  1.021397  0.172707 -0.580595  0.729541

In [44]:
df2=df.copy()
df2["E"]=[2,3,4,3,2,5]
df2[df2["E"].isin([2,3])]

                   A         B         C         D  E
2013-01-01  0.669801  1.048827 -1.585766 -0.749194  2
2013-01-02  0.757677  0.262206  1.266002  1.030052  3
2013-01-04  1.021397  0.172707 -0.580595  0.729541  3
2013-01-05 -0.922721  0.722249  1.438161 -0.833204  2

In [45]:
# 赋值
df.at[dates[0],'A']=0
df.iat[0,1]=0.2
df.loc[:,'D']=[5]*len(df)
df

                   A         B         C  D
2013-01-01  0.000000  0.200000 -1.585766  5
2013-01-02  0.757677  0.262206  1.266002  5
2013-01-03  1.976971  0.787396  0.455361  5
2013-01-04  1.021397  0.172707 -0.580595  5
2013-01-05 -0.922721  0.722249  1.438161  5
2013-01-06 -0.200188  1.524352  0.238962  5

In [46]:
df2=df.copy()
# 对大于0的单元格取负值
df2[df2>0]=-df2
df2

                   A         B         C  D
2013-01-01  0.000000 -0.200000 -1.585766 -5
2013-01-02 -0.757677 -0.262206 -1.266002 -5
2013-01-03 -1.976971 -0.787396 -0.455361 -5
2013-01-04 -1.021397 -0.172707 -0.580595 -5
2013-01-05 -0.922721 -0.722249 -1.438161 -5
2013-01-06 -0.200188 -1.524352 -0.238962 -5

### 缺省值